baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Gasthof-Pension Spessartruh Steiger'
theme = "spessartruhTheme"
defaultContentLanguage = "de"

################### German Navigation ########################

[[Languages.de.menu.main]]
name = "Speisekarte"
url = "/menu"
weight = 2

[[Languages.de.menu.main]]
name = "Zimmer & Suite"
url = "/rooms"
weight = 3



[[Languages.de.menu.main]]
name = "Anfahrt"
url = "/location"
weight = 5

[[Languages.de.menu.main]]
name = "Datenschutz"
url = "/location"
weight = 12

[[Languages.de.menu.main]]
name = "Impressum"
url = "/location"
weight = 13 

[[Languages.de.menu.main]]
name = "Jobs"
url = "/location"
weight = 14 




################################ German Language ########################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2022 Musikverein Sailauf"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-en"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2022 Musikverein Sailauf"

[params]
formspark_form_id = "v2KI1ERx"
contrast_color = "#8ab42f"