baseURL = 'https://gasthofspessartruh.github.io'
languageCode = 'en-us'
title = 'Gasthof Spessartruh Steiger'
theme = "spessartruhTheme"
defaultContentLanguage = "de"
timeout = "10m"
################### German Navigation ########################

[[Languages.de.menu.main]]
name = "Speisekarte"
url = "/menu"
weight = 2

[[Languages.de.menu.main]]
name = "Gästezimmer"
url = "/rooms"
weight = 3

[[Languages.de.menu.main]]
name = "Panorama"
url = "/panorama"
weight = 4

[[Languages.de.menu.main]]
name = "Anfahrt"
url = "/location"
weight = 5

[[Languages.de.menu.main]]
name = "Gut zu Wissen"
url = "/faq"
weight = 6 

[[Languages.de.menu.main]]
name = "Datenschutz"
url = "/dsgvo"
weight = 12

[[Languages.de.menu.main]]
name = "Impressum"
url = "/impress"
weight = 13 

[[Languages.de.menu.main]]
name = "Jobs"
url = "/jobs"
weight = 14 

[[Languages.en.menu.main]]
name = "Menu"
url = "/menu"
weight = 2

[[Languages.en.menu.main]]
name = "Rooms"
url = "/rooms"
weight = 3

[[Languages.en.menu.main]]
name = "Panorama"
url = "/panorama"
weight = 4

[[Languages.en.menu.main]]
name = "Directions"
url = "/location"
weight = 5

[[Languages.en.menu.main]]
name = "FAQ"
url = "/faq"
weight = 6

[[Languages.en.menu.main]]
name = "Privacy Policy"
url = "/dsgvo"
weight = 12

[[Languages.en.menu.main]]
name = "Imprint"
url = "/impress"
weight = 13 

[[Languages.en.menu.main]]
name = "Jobs"
url = "/jobs"
weight = 14 




################################ German Language ########################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 1

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-en"
contentDir = "content/english"
weight = 2

[params]
formspark_form_id = "ziXjlqs59"
contrast_color = "#8ab42f"
contrast_red_color = "#a12312"
notification_color ="#6a8530"